/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul6;

/**
 *
 * @author Ardelya
 */
public class lat5 extends javax.swing.JFrame {

    /**
     * Creates new form lat5
     */
    public lat5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dokter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spesialis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        goldar = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        warga = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PEMILIHAN DOKTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 200, 60);

        dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. Farras Yassar", "DR. Dian Sikahita", "DR. Harun Ulum Fajar" }));
        dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterActionPerformed(evt);
            }
        });
        getContentPane().add(dokter);
        dokter.setBounds(120, 60, 140, 20);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 50, 150, 50);

        jLabel3.setText("Kewarganegaraan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 330, 100, 14);

        jLabel4.setText("Identitas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 90, 14);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 140, 27, 14);

        jLabel6.setText("Status");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 300, 50, 14);

        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 180, 33, 14);

        jLabel8.setText("Usia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 210, 20, 14);

        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 140, 14);

        jLabel10.setText("Golongan Darah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 270, 80, 14);

        jLabel11.setText("Dokter Spesialis");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 410, 110, 14);

        jLabel12.setText("Waktu Praktek");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 370, 90, 14);
        getContentPane().add(spesialis);
        spesialis.setBounds(120, 410, 160, 20);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(120, 140, 160, 20);
        getContentPane().add(alamat);
        alamat.setBounds(120, 170, 160, 20);
        getContentPane().add(usia);
        usia.setBounds(120, 200, 160, 20);
        getContentPane().add(jenis);
        jenis.setBounds(120, 230, 160, 20);
        getContentPane().add(goldar);
        goldar.setBounds(120, 260, 160, 20);
        getContentPane().add(status);
        status.setBounds(120, 290, 160, 20);
        getContentPane().add(warga);
        warga.setBounds(120, 330, 160, 20);
        getContentPane().add(waktu);
        waktu.setBounds(120, 370, 160, 20);

        setBounds(0, 0, 450, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterActionPerformed
        // TODO add your handling code here:
        if (dokter.getSelectedItem().equals("DR. Farras Yassar")){
            nama.setText("DR. Farras Yassar ");
            alamat.setText("Jl. Surabaya 16, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Laki-Laki");
            goldar.setText("A");
            status.setText("Belum Menikah ");
            warga.setText("Indonesia");
            spesialis.setText("Dokter Umum");
            waktu.setText(" Pagi (07.00-15.00)");
        }
        else
        if(dokter.getSelectedItem().equals("DR. Dian Sikahita")){
            nama.setText("DR. Dian Sikahita");
            alamat.setText("Jl. Veteran 3, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Perempuan");
            goldar.setText("O");
            status.setText("Belum Menikah");
            warga.setText("Indonesia");
            spesialis.setText("Dokter Gigi");
            waktu.setText(" Malam (16.00-22.00)");}
        else
        if(dokter.getSelectedItem().equals("DR. Harun Ulum Fajar")){
            nama.setText("DR. Harun Ulum Fajar");
            alamat.setText("Jl. Bandung 9, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Laki-Laki");
            goldar.setText("B");
            status.setText("Belum Menikah");
            warga.setText("Indonesia");
            spesialis.setText("Dokter Gizi");
            waktu.setText(" Malam (22.00-06.00)");
        }

    }//GEN-LAST:event_dokterActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lat5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> dokter;
    private javax.swing.JTextField goldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField spesialis;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktu;
    private javax.swing.JTextField warga;
    // End of variables declaration//GEN-END:variables
}
