/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul6;

/**
 *
 * @author Ardelya
 */
public class prak2 extends javax.swing.JFrame {
    String jns= "";
    int jml;
    /**
     * Creates new form prak2
     */
    public prak2() {
        initComponents();
        getjumlah();
        setjenis();
        pilihanbil.setEnabled(false);
        tiga.setVisible(false);
        b3.setVisible(false);
        empat.setVisible(false);
        b4.setVisible(false);
        satu.setVisible(false);
        b1.setVisible(false);
        dua.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        empat = new javax.swing.JTextField();
        satu = new javax.swing.JTextField();
        dua = new javax.swing.JTextField();
        tiga = new javax.swing.JTextField();
        b4 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Program Aritmatika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 91, 14);

        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 100, 14);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\t", "Pengurangan", "Penjumlahan", "Pembagian", "Perkalian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(270, 50, 130, 20);

        jLabel3.setText("Operasi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 80, 14);
        getContentPane().add(label);
        label.setBounds(130, 110, 190, 20);

        jLabel5.setText("Jumlah Bilangan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 100, 14);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        getContentPane().add(pilihanbil);
        pilihanbil.setBounds(160, 150, 170, 20);
        getContentPane().add(empat);
        empat.setBounds(160, 240, 170, 20);
        getContentPane().add(satu);
        satu.setBounds(160, 180, 170, 20);
        getContentPane().add(dua);
        dua.setBounds(160, 200, 170, 20);
        getContentPane().add(tiga);
        tiga.setBounds(160, 220, 170, 20);

        b4.setText("Bilangan 4");
        getContentPane().add(b4);
        b4.setBounds(84, 240, 70, 14);

        b1.setText("Bilangan 1");
        getContentPane().add(b1);
        b1.setBounds(84, 180, 70, 14);

        b2.setText("Bilangan 2");
        getContentPane().add(b2);
        b2.setBounds(84, 200, 70, 14);

        b3.setText("Bilangan 3");
        getContentPane().add(b3);
        b3.setBounds(84, 220, 70, 14);

        ok.setText("Submit");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(200, 280, 90, 23);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane2.setViewportView(hasil);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 320, 370, 96);

        setBounds(0, 0, 495, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setjenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        // TODO add your handling code here:
        getjumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        double hsl =0.0;
        double a1, a2, a3, a4;
        
        a1 = Double.parseDouble(satu.getText().toString());
        a2 = Double.parseDouble(satu.getText().toString());
        a3 = Double.parseDouble(satu.getText().toString());
        a4 = Double.parseDouble(satu.getText().toString());
        
        if (jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1+a2;
                hasil.setText(""+a1+" + "+a2+" = "+hsl);
            }
            if(jml == 3){
                hsl = a1+a2+a3;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" = "+hsl);
            }
            if(jml == 4){
                hsl = a1+a2+a3+a4;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" + "+a4+" = "+hsl);
            }
        }
        if (jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1-a2;
                hasil.setText(""+a1+" - "+a2+" = "+hsl);
            }
            if(jml == 3){
                hsl = a1-a2-a3;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" = "+hsl);
            }
            if(jml == 4){
                hsl = a1-a2-a3-a4;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" - "+a4+" = "+hsl);
            }
        }
        if (jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1*a2;
                hasil.setText(""+a1+" x "+a2+" = "+hsl);
            }
            if(jml == 3){
                hsl = a1*a2*a3;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" = "+hsl);
            }
            if(jml == 4){
                hsl = a1*a2*a3*a4;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" x "+a4+" = "+hsl);
            }
        }
        if (jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1/a2;
                hasil.setText(""+a1+" / "+a2+" = "+hsl);
            }
            if(jml == 3){
                hsl = a1/a2/a3;
                hasil.setText(""+a1+" / "+a2+" / "+a3+" = "+hsl);
            }
            if(jml == 4){
                hsl = a1/a2/a3/a4;
                hasil.setText(""+a1+" / "+a2+" / "+a3+" / "+a4+" = "+hsl);
            }
        }
    }//GEN-LAST:event_okActionPerformed

    public void setjenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            label.setText("Penjumlahan");
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            label.setText("Pengurangan");
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            label.setText("Perkalian");
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            label.setText("Pembagian");
            pilihanbil.setEnabled(true);
        }
    }
    
    public void getjumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
            b3.setVisible(false);
            b4.setVisible(false);
            tiga.setVisible(false);
            empat.setVisible(false);
            b2.setVisible(true);
            b1.setVisible(true);
            satu.setVisible(true);
            dua.setVisible(true);
            jml = 2;
        }
        else if(pilihanbil.getSelectedItem().equals("3")){
            b3.setVisible(true);
            b4.setVisible(false);
            tiga.setVisible(true);
            empat.setVisible(false);
            b2.setVisible(true);
            b1.setVisible(true);
            satu.setVisible(true);
            dua.setVisible(true);
            jml = 3;
        }
        else if(pilihanbil.getSelectedItem().equals("4")){
            b3.setVisible(true);
            b4.setVisible(true);
            tiga.setVisible(true);
            empat.setVisible(true);
            b2.setVisible(true);
            b1.setVisible(true);
            satu.setVisible(true);
            dua.setVisible(true);
            jml = 4;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prak2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField dua;
    private javax.swing.JTextField empat;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel label;
    private javax.swing.JButton ok;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField satu;
    private javax.swing.JTextField tiga;
    // End of variables declaration//GEN-END:variables
}
